version: '3.8'

services:
  postgresql:
    image: postgres:15
    container_name: securitymodel_postgres
    environment:
      POSTGRES_DB: secmodel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: n7cuellar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - securitymodel_network

volumes:
  postgres_data:

networks:
  securitymodel_network:
    driver: bridge