version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: securitymodel_sqlserver
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: StrongPassword123!
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - securitymodel_network

volumes:
  sqlserver_data:

networks:
  securitymodel_network:
    driver: bridge