version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: securitymodel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: securitymodel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - securitymodel_network

volumes:
  mysql_data:

networks:
  securitymodel_network:
    driver: bridge